#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

rm -rf $1/app/AllshareFileShare
rm -rf $1/app/AllshareMediaShare
rm -rf $1/app/AmazonMDIP_USA
rm -rf $1/app/AmazonShopping_USA
rm -rf $1/app/AmazonVideo_SPR_stub
rm -rf $1/app/BBCAgent
rm -rf $1/app/BCService
rm -rf $1/app/CarmodeStub
rm -rf $1/app/ChocoEUKor
rm -rf $1/app/ClipboardEdge
rm -rf $1/app/CnnPanel
rm -rf $1/app/CocktailQuickTool
rm -rf $1/app/CoolEUKor
rm -rf $1/app/EasyOneHand3
rm -rf $1/app/EasymodeContactsWidget81
rm -rf $1/app/FBAppManager_NS
rm -rf $1/app/Facebook_stub
rm -rf $1/app/FlipboardBriefing
rm -rf $1/app/Foundation
rm -rf $1/app/GameOptimizer
rm -rf $1/app/GameOptimizingService
rm -rf $1/app/GearManagerStub
rm -rf $1/app/Gmail2
rm -rf $1/app/KidsHome_Installer
rm -rf $1/app/KnoxAttestationAgent
rm -rf $1/app/KnoxKeyChain
rm -rf $1/app/LinkSharing_v10
rm -rf $1/app/Maps
rm -rf $1/app/MirrorLink
rm -rf $1/app/MotionPanoramaViewer
rm -rf $1/app/Panorama360Viewer
rm -rf $1/app/RoseEUKor
rm -rf $1/app/SBrowserEdge
rm -rf $1/app/SBrowser_9.0
rm -rf $1/app/SamsungPassAutofill_v1
rm -rf $1/app/SamsungTTS
rm -rf $1/app/SelfMotionPanoramaViewer
rm -rf $1/app/SmartMirroring
rm -rf $1/app/SmartReminder
rm -rf $1/app/SmartSwitchAgent
rm -rf $1/app/StoryEditor_Dream_N
rm -rf $1/app/VideoEditorLite_Dream_N
rm -rf $1/app/VideoTrimmer
rm -rf $1/app/VisionIntelligence2
rm -rf $1/app/Weather_SEP10.1
rm -rf $1/app/YahooEdgeFinance
rm -rf $1/app/YahooEdgeSports
rm -rf $1/app/YelpPanel
rm -rf $1/app/YouTube
rm -rf $1/carrier
rm -rf $1/container
rm -rf $1/etc/autorun.iso
rm -rf $1/hidden
rm -rf $1/priv-app/AODService_v40
rm -rf $1/priv-app/AppsEdgePanel_v3.2
rm -rf $1/priv-app/AssistantMenu_N
rm -rf $1/priv-app/BeaconManager
rm -rf $1/priv-app/BioFaceService
rm -rf $1/priv-app/BlueLightFilter
rm -rf $1/priv-app/CocktailBarService_v3.2
rm -rf $1/priv-app/ContainerAgent3
rm -rf $1/priv-app/DesktopModeUiService
rm -rf $1/priv-app/DexCommunity
rm -rf $1/priv-app/DualOutFocusViewer
rm -rf $1/priv-app/FBInstaller_NS
rm -rf $1/priv-app/Finder
rm -rf $1/priv-app/Fmm
rm -rf $1/priv-app/FotaAgent
rm -rf $1/priv-app/GalaxyAppsWidget_Phone_Dream
rm -rf $1/priv-app/GalaxyApps_OPEN
rm -rf $1/priv-app/GameHome
rm -rf $1/priv-app/GameTools_Dream
rm -rf $1/priv-app/Gear360Editor_Beyond
rm -rf $1/priv-app/GearVRService
rm -rf $1/priv-app/HancomOfficeEditor_Hidden_Install
rm -rf $1/priv-app/HealthService
rm -rf $1/priv-app/Hearingdro_V7_P
rm -rf $1/priv-app/KnoxContainerDesktop
rm -rf $1/priv-app/KnoxCore
rm -rf $1/priv-app/KnoxDesktopLauncher
rm -rf $1/priv-app/KnoxGuard
rm -rf $1/priv-app/LedCoverAppStar
rm -rf $1/priv-app/LedCoverService
rm -rf $1/priv-app/LinkedIn_SamsungStub
rm -rf $1/priv-app/PeopleStripe
rm -rf $1/priv-app/SKMSAgent
rm -rf $1/priv-app/SVoiceIME
rm -rf $1/priv-app/SVoicePLM
rm -rf $1/priv-app/SamsungBilling
rm -rf $1/priv-app/SamsungMagnifier3
rm -rf $1/priv-app/SamsungPass
rm -rf $1/priv-app/SamsungSocial
rm -rf $1/priv-app/SecEmail_P
rm -rf $1/priv-app/SmartSwitchAssistant
rm -rf $1/priv-app/SoundAlive_54
rm -rf $1/priv-app/TaskEdgePanel_v3.2
rm -rf $1/priv-app/TmoVVM
rm -rf $1/priv-app/TouchWizHome_2017
rm -rf $1/priv-app/VZWAPNService_sku
rm -rf $1/priv-app/VzCloud
rm -rf $1/priv-app/knoxanalyticsagent
rm -rf $1/priv-app/knoxvpnproxyhandler
rm -rf $1/saiv
rm -rf $1/tima_measurement_info
rm -rf $1/voicebargeindata
