# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apex_build_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apex_build_info.proto',
  package='apex.proto',
  syntax='proto3',
  serialized_options=b'\n\020com.android.apexB\006Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x61pex_build_info.proto\x12\napex.proto\"\x95\x02\n\rApexBuildInfo\x12\x1b\n\x13\x61pexer_command_line\x18\x01 \x01(\t\x12\x15\n\rfile_contexts\x18\x02 \x01(\x0c\x12\x18\n\x10\x63\x61nned_fs_config\x18\x03 \x01(\x0c\x12\x18\n\x10\x61ndroid_manifest\x18\x04 \x01(\x0c\x12\x17\n\x0fmin_sdk_version\x18\x05 \x01(\t\x12\x1a\n\x12target_sdk_version\x18\x06 \x01(\t\x12\x13\n\x0bno_hashtree\x18\x07 \x01(\x08\x12!\n\x19override_apk_package_name\x18\x08 \x01(\t\x12\x16\n\x0elogging_parent\x18\t \x01(\t\x12\x17\n\x0fpayload_fs_type\x18\n \x01(\tB\x1a\n\x10\x63om.android.apexB\x06Protosb\x06proto3'
)




_APEXBUILDINFO = _descriptor.Descriptor(
  name='ApexBuildInfo',
  full_name='apex.proto.ApexBuildInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='apexer_command_line', full_name='apex.proto.ApexBuildInfo.apexer_command_line', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_contexts', full_name='apex.proto.ApexBuildInfo.file_contexts', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='canned_fs_config', full_name='apex.proto.ApexBuildInfo.canned_fs_config', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='android_manifest', full_name='apex.proto.ApexBuildInfo.android_manifest', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_sdk_version', full_name='apex.proto.ApexBuildInfo.min_sdk_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_sdk_version', full_name='apex.proto.ApexBuildInfo.target_sdk_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='no_hashtree', full_name='apex.proto.ApexBuildInfo.no_hashtree', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='override_apk_package_name', full_name='apex.proto.ApexBuildInfo.override_apk_package_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logging_parent', full_name='apex.proto.ApexBuildInfo.logging_parent', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload_fs_type', full_name='apex.proto.ApexBuildInfo.payload_fs_type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=315,
)

DESCRIPTOR.message_types_by_name['ApexBuildInfo'] = _APEXBUILDINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApexBuildInfo = _reflection.GeneratedProtocolMessageType('ApexBuildInfo', (_message.Message,), {
  'DESCRIPTOR' : _APEXBUILDINFO,
  '__module__' : 'apex_build_info_pb2'
  # @@protoc_insertion_point(class_scope:apex.proto.ApexBuildInfo)
  })
_sym_db.RegisterMessage(ApexBuildInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
